2017-11-21 17:46:42,266 runAll.py[line:83] INFO ********测试 开始！********
2017-11-21 17:46:42,266 runAll.py[line:90] ERROR 'list' object is not callable
2017-11-21 17:46:42,266 runAll.py[line:92] INFO *********测试 结束！*********
2017-11-21 17:46:42,267 runAll.py[line:101] INFO 不需要发动邮件给任何人！
